### ISSUE TITLE
Emphasise sidebar section headings

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/quarto-course-template#9]
On the left-hand `sidebar`, try to make the section headings have more emphasis (e.g. bold, or underlined, or larger). 
Probably needs to be done via the css file.

**Comment by mvanrongen** [comment]
Note: just adding markdown bold to the section name works as a lazy option, e.g. `"**section_title**"`

**Comment by tavareshugo** [comment]
I'll close this then and leave this as optional to each person
